# Generated by Django 5.1.1 on 2024-09-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=12, verbose_name='NIT.')),
                ('nombreEdificio', models.CharField(max_length=80, verbose_name='Nombre Edificio')),
                ('dirEdificio', models.CharField(max_length=100, verbose_name='Dirección Edificio')),
                ('telAdmon', models.CharField(max_length=10, verbose_name='Teléfono Admón')),
                ('correoAdmon', models.CharField(max_length=100, verbose_name='Correo Admón')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProd', models.CharField(max_length=20, verbose_name='Descripcion del Producto')),
                ('modeloProd', models.CharField(default='', max_length=50, verbose_name='Modelo del Producto')),
                ('fotoProd', models.ImageField(null=True, upload_to='img/', verbose_name='Foto Producto')),
                ('marcaProd', models.CharField(max_length=80, verbose_name='Marca Camara')),
            ],
        ),
    ]
