# Generated by Django 5.0.4 on 2024-09-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=12, verbose_name='NIT.')),
                ('nombreEdificio', models.CharField(max_length=80, verbose_name='Nombre Edificio')),
                ('dirEdificio', models.CharField(max_length=100, verbose_name='Dirección Edificio')),
                ('telAdmon', models.CharField(max_length=10, verbose_name='Teléfono Admón')),
                ('correoAdmon', models.CharField(max_length=100, verbose_name='Correo Admón')),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProd', models.CharField(max_length=20, verbose_name='Descripcion del Producto')),
                ('modeloProd', models.CharField(default='', max_length=50, verbose_name='Modelo del Producto')),
                ('fotoProd', models.ImageField(null=True, upload_to='img/', verbose_name='Foto Producto')),
                ('marcaProd', models.CharField(max_length=80, verbose_name='Marca Camara')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('idSold', models.AutoField(primary_key=True, serialize=False)),
                ('nitSold', models.CharField(max_length=12, verbose_name='NIT')),
                ('fecha_de_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('nombre_cliente', models.CharField(max_length=80, verbose_name='Nombre Cliente')),
                ('nombre_edificio', models.CharField(max_length=100, verbose_name='Nombre Edificio')),
                ('ciudad_cliente', models.CharField(max_length=40, verbose_name='Ciudad')),
                ('direccion_cliente', models.CharField(max_length=40, verbose_name='Dirección')),
                ('tel_admin', models.CharField(max_length=20, verbose_name='Teléfono Admin')),
                ('correo_admin', models.EmailField(max_length=254, verbose_name='Correo Admin')),
            ],
        ),
    ]
