# Generated by Django 5.1.1 on 2024-09-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=12, verbose_name='NIT')),
                ('fecha_de_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('nombre_cliente', models.CharField(max_length=80, verbose_name='Nombre Cliente')),
                ('nombre_edificio', models.CharField(max_length=100, verbose_name='Nombre Edificio')),
                ('ciudad_cliente', models.CharField(max_length=40, verbose_name='Ciudad')),
                ('direccion_cliente', models.CharField(max_length=40, verbose_name='Dirección')),
                ('tel_admin', models.CharField(max_length=20, verbose_name='Teléfono Admin')),
                ('correo_admin', models.EmailField(max_length=254, verbose_name='Correo Admin')),
            ],
        ),
    ]
