# Generated by Django 5.1.1 on 2024-09-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0002_solicitudes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitudes',
            new_name='solicitud',
        ),
    ]
