# Generated by Django 5.1.1 on 2024-09-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0003_rename_solicitudes_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='id',
            new_name='idSold',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='nit',
            new_name='nitSold',
        ),
    ]
